# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class ApiKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """API kind."""

    REST = "rest"
    """REST API"""
    GRAPHQL = "graphql"
    """GraphQL API"""
    GRPC = "grpc"
    """GRPC API"""
    SOAP = "soap"
    """SOAP API"""
    WEBHOOK = "webhook"
    """Webhook API"""
    WEBSOCKET = "websocket"
    """Websocket API"""


class ApiSpecExportResultFormat(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Export specification result format."""

    LINK = "link"
    """Link format"""


class EnvironmentKind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Environment kind."""

    DEVELOPMENT = "development"
    """Environment is in the development stage"""
    TESTING = "testing"
    """Environment is in the testing stage"""
    STAGING = "staging"
    """Environment is in the staging stage"""
    PRODUCTION = "production"
    """Environment is in the production stage"""


class LifecycleStage(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """API Lifecycle Stage."""

    DESIGN = "design"
    """API is in the design stage"""
    DEVELOPMENT = "development"
    """API is in the development stage"""
    TESTING = "testing"
    """API is in the testing stage"""
    PREVIEW = "preview"
    """API is in the preview stage"""
    PRODUCTION = "production"
    """API is in the production stage"""
    DEPRECATED = "deprecated"
    """API is in the deprecated stage"""
    RETIRED = "retired"
    """API is in the retired stage"""
