# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models_py3 import ErrorAdditionalInfo
from ._models_py3 import ErrorDetail
from ._models_py3 import ErrorResponse
from ._models_py3 import ExecutionConstraints
from ._models_py3 import ExecutionTarget
from ._models_py3 import ExecutionTrigger
from ._models_py3 import ProxyResource
from ._models_py3 import Resource
from ._models_py3 import ResourceAutoGenerated
from ._models_py3 import StorageTaskAssignment
from ._models_py3 import StorageTaskAssignmentCreateParameters
from ._models_py3 import StorageTaskAssignmentExecutionContext
from ._models_py3 import StorageTaskAssignmentReport
from ._models_py3 import StorageTaskAssignmentUpdateParameters
from ._models_py3 import StorageTaskAssignmentsList
from ._models_py3 import StorageTaskReportInstance
from ._models_py3 import StorageTaskReportProperties
from ._models_py3 import StorageTaskReportSummary
from ._models_py3 import SystemData
from ._models_py3 import TrackedResource
from ._models_py3 import TriggerParameters

from ._storage_task_assignments_management_client_enums import CreatedByType
from ._storage_task_assignments_management_client_enums import ProvisioningState
from ._storage_task_assignments_management_client_enums import RunResult
from ._storage_task_assignments_management_client_enums import RunStatusEnum
from ._storage_task_assignments_management_client_enums import Type
from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "ErrorAdditionalInfo",
    "ErrorDetail",
    "ErrorResponse",
    "ExecutionConstraints",
    "ExecutionTarget",
    "ExecutionTrigger",
    "ProxyResource",
    "Resource",
    "ResourceAutoGenerated",
    "StorageTaskAssignment",
    "StorageTaskAssignmentCreateParameters",
    "StorageTaskAssignmentExecutionContext",
    "StorageTaskAssignmentReport",
    "StorageTaskAssignmentUpdateParameters",
    "StorageTaskAssignmentsList",
    "StorageTaskReportInstance",
    "StorageTaskReportProperties",
    "StorageTaskReportSummary",
    "SystemData",
    "TrackedResource",
    "TriggerParameters",
    "CreatedByType",
    "ProvisioningState",
    "RunResult",
    "RunStatusEnum",
    "Type",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
