# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class CreatedByType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of identity that created the resource."""

    USER = "User"
    APPLICATION = "Application"
    MANAGED_IDENTITY = "ManagedIdentity"
    KEY = "Key"


class ManagedServiceIdentityType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of managed service identity (where both SystemAssigned and UserAssigned types are
    allowed).
    """

    NONE = "None"
    SYSTEM_ASSIGNED = "SystemAssigned"
    USER_ASSIGNED = "UserAssigned"
    SYSTEM_ASSIGNED_USER_ASSIGNED = "SystemAssigned,UserAssigned"


class PermissionType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The requested permission."""

    CONTRIBUTOR = "Contributor"
    READER = "Reader"


class ProvisioningState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Gets the status of the account at the time the operation was called."""

    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    CANCELED = "Canceled"
    ACCEPTED = "Accepted"
    PROVISIONING = "Provisioning"
    DELETING = "Deleting"


class Reason(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Gets the reason that a Video Indexer account name could not be used. The Reason element is only
    returned if NameAvailable is false.
    """

    ALREADY_EXISTS = "AlreadyExists"


class Scope(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The requested media type."""

    VIDEO = "Video"
    ACCOUNT = "Account"
    PROJECT = "Project"


class Type(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of resource, Microsoft.VideoIndexer/accounts."""

    MICROSOFT_VIDEO_INDEXER_ACCOUNTS = "Microsoft.VideoIndexer/accounts"
