# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models_py3 import AddCustomLocationDetails
from ._models_py3 import DisableExtensionsRequestDetails
from ._models_py3 import EnableExtensionsRequestDetails
from ._models_py3 import ErrorAdditionalInfo
from ._models_py3 import ErrorDetail
from ._models_py3 import ErrorResponse
from ._models_py3 import ExtensionManager
from ._models_py3 import ExtensionManagerListResult
from ._models_py3 import ExtensionManagerPatch
from ._models_py3 import ExtensionObject
from ._models_py3 import ManagedIdentity
from ._models_py3 import ManagedIdentityUpdate
from ._models_py3 import Operation
from ._models_py3 import OperationDisplay
from ._models_py3 import OperationListResult
from ._models_py3 import RemoveCustomLocationDetails
from ._models_py3 import Resource
from ._models_py3 import ScenarioProfileObject
from ._models_py3 import SystemData
from ._models_py3 import TrackedResource

from ._hybrid_onboarding_mgmt_client_enums import ActionType
from ._hybrid_onboarding_mgmt_client_enums import CreatedByType
from ._hybrid_onboarding_mgmt_client_enums import ExtensionState
from ._hybrid_onboarding_mgmt_client_enums import ManagedIdentityType
from ._hybrid_onboarding_mgmt_client_enums import Origin
from ._hybrid_onboarding_mgmt_client_enums import ProvisioningState
from ._hybrid_onboarding_mgmt_client_enums import Versions
from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "AddCustomLocationDetails",
    "DisableExtensionsRequestDetails",
    "EnableExtensionsRequestDetails",
    "ErrorAdditionalInfo",
    "ErrorDetail",
    "ErrorResponse",
    "ExtensionManager",
    "ExtensionManagerListResult",
    "ExtensionManagerPatch",
    "ExtensionObject",
    "ManagedIdentity",
    "ManagedIdentityUpdate",
    "Operation",
    "OperationDisplay",
    "OperationListResult",
    "RemoveCustomLocationDetails",
    "Resource",
    "ScenarioProfileObject",
    "SystemData",
    "TrackedResource",
    "ActionType",
    "CreatedByType",
    "ExtensionState",
    "ManagedIdentityType",
    "Origin",
    "ProvisioningState",
    "Versions",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
