# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class ApiLifecycleStage(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """API Lifecycle Stage."""

    DESIGN = "design"
    """API is in the design stage"""
    DEVELOPMENT = "development"
    """API is in the development stage"""
    TESTING = "testing"
    """API is in the testing stage"""
    PREVIEW = "preview"
    """API is in the preview stage"""
    PRODUCTION = "production"
    """API is in the production stage"""
    DEPRECATED = "deprecated"
    """API is in the deprecated stage"""
    RETIRED = "retired"
    """API is in the retired stage"""
