# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._operations import FaceListsOperations
from ._operations import LargeFaceListsOperations
from ._operations import FaceAsyncOperationsOperations
from ._operations import PersonDirectoryPersonsOperations
from ._operations import PersonDirectoryDynamicPersonGroupsOperations
from ._operations import PersonGroupsOperations
from ._operations import LargePersonGroupsOperations
from ._operations import LivenessSessionsOperations
from ._operations import LivenessWithVerifySessionsOperations
from ._operations import FaceClientOperationsMixin

from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "FaceListsOperations",
    "LargeFaceListsOperations",
    "FaceAsyncOperationsOperations",
    "PersonDirectoryPersonsOperations",
    "PersonDirectoryDynamicPersonGroupsOperations",
    "PersonGroupsOperations",
    "LargePersonGroupsOperations",
    "LivenessSessionsOperations",
    "LivenessWithVerifySessionsOperations",
    "FaceClientOperationsMixin",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
